# refer project structure components of [main, core, utils]: https://www.github.com/dollarkillerx/Simple-blockchain/tree/master/ 

[workspace]
members = [
	"main",
	"core",
	"utils",
	"sample",
	"utils/hashing-utils",
	"sample02",
	"sample03",
]
